version: "3"
services:
    nginx:
        build:
            args:
                NGINX_VERSION: ${NGINX_VERSION}
            context: ./config/nginx
        container_name: nginx
        depends_on:
            - php
        environment:
            TZ: $TZ
        networks:
            - frontend
        ports:
            - "${NGINX_HTTP_HOST_PORT}:80"
            - "${NGINX_HTTPS_HOST_PORT}:443"
        restart: always
        volumes:
            - ${SRC_DIR}:/var/www/html/:rw
            - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
            - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
            - ${NGINX_LOG_DIR}:/var/log/nginx/:rw

networks:
    backend:
    frontend:
