version: "3"
services:
    nginx:
        build:
            args:
                NGINX_VERSION: ${NGINX_VERSION}
            context: ./config/nginx
        container_name: nginx
        depends_on:
            - php
        environment:
            TZ: $TZ
        networks:
            - frontend
        ports:
            - "${NGINX_HTTP_HOST_PORT}:80"
            - "${NGINX_HTTPS_HOST_PORT}:443"
        restart: always
        volumes:
            - ${SRC_DIR}:/var/www/html/:rw
            - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:ro
            - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
            - ${NGINX_LOG_DIR}:/var/log/nginx/:rw

    php:
        build:
            args:
                ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
                PHP_VERSION: ${PHP_VERSION}
                PHP_REDIS_VERSION: ${PHP_REDIS_VERSION}
            context: ./config/php
        cap_add:
            - SYS_PTRACE
        container_name: php
        environment:
            TZ: $TZ
        networks:
            - backend
            - frontend
        ports:
            - "${PHP_HOST_PORT}:9000"
        restart: always
        volumes:
            - ${SRC_DIR}:/var/www/html/:rw
            - ${PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
            - ${PHP_FPM_CONF_FILE}:/usr/local/etc/php/php-fpm.conf:ro
            - ${PHP_LOG_DIR}:/var/log/php/:rw

    mysql:
        build:
            args:
                MYSQL_VERSION: ${MYSQL_VERSION}
            context: ./config/mysql
        container_name: mysql
        environment:
            TZ: $TZ
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        networks:
            - backend
        ports:
            - "${MYSQL_HOST_PORT}:3306"
        restart: always
        volumes:
            - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.conf:ro
            - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw

networks:
    backend:
    frontend:
